version: '2'
services:
    es-master:
        labels: 
            - io.rancher.container.hostname_override=container_name
            - io.rancher.sidekicks=es-storage
        image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
        environment: 
            - "cluster.name=${cluster_name}"
            - "node.name=$${HOSTNAME}"
            - "bootstrap.memory_lock=true"
            - "xpack.security.enabled=false"
            - "ES_JAVA_OPTS=-Xms${master_heap_size} -Xmx${master_heap_size}"
            - "discovery.zen.ping.unicast.hosts=es-master"
            - "discovery.zen.minimum_master_nodes=${minimum_master_nodes}"
            - "node.master=true"
            - "node.data=false"
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: ${master_mem_limit}
        mem_swappiness: 0
        cap_add: 
            - IPC_LOCK
        volumes_from: 
            - es-storage

    es-data:
        labels:
            - io.rancher.container.hostname_override=container_name
            - io.rancher.sidekicks=es-storage
        image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
        environment: 
            - "cluster.name=${cluster_name}"
            - "node.name=$${HOSTNAME}"
            - "bootstrap.memory_lock=true"
            - "xpack.security.enabled=false"
            - "discovery.zen.ping.unicast.hosts=es-master"
            - "ES_JAVA_OPTS=-Xms${data_heap_size} -Xmx${data_heap_size}"
            - "node.master=false"
            - "node.data=true"
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: ${data_mem_limit}
        mem_swappiness: 0
        cap_add: 
            - IPC_LOCK
        volumes_from: 
            - es-storage
        depends_on: 
            - es-master

    es-client:
        labels:
            - io.rancher.container.hostname_override=container_name
            - io.rancher.sidekicks=es-storage
        image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
        environment: 
            - "cluster.name=${cluster_name}"
            - "node.name=$${HOSTNAME}"
            - "bootstrap.memory_lock=true"
            - "xpack.security.enabled=false"
            - "discovery.zen.ping.unicast.hosts=es-master"
            - "ES_JAVA_OPTS=-Xms${client_heap_size} -Xmx${client_heap_size}"
            - "node.master=false"
            - "node.data=false"
        ulimits: 
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: ${client_mem_limit}
        mem_swappiness: 0
        cap_add: 
            - IPC_LOCK
        volumes_from: 
            - es-storage
        depends_on: 
            - es-master
    
    es-storage:
        labels:
            - io.rancher.container.start_once=true
        image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
        entrypoint: /bin/true
        volumes: 
            - es-storage-volume:/usr/share/elasticsearch/data

    kopf:
      image: sandinh/kopf:2.1.2-1
      ports:
        - ${kopf_port}:8000
      environment:
        KOPF_SERVER_NAME: ${cluster_name}
        KOPF_ES_SERVERS: 'es-client:9200'
        KOPF_BASIC_AUTH_LOGIN: admin
        KOPF_BASIC_AUTH_PASSWORD: ${kopf_pw}
      labels:
        io.rancher.container.hostname_override: container_name
      links:
        - elasticsearch-clients:es-client

volumes:
  es-storage-volume:
    driver: local
    per_container: true